steps:
  # Build the container image (Global Region: us-west1)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/images/api:$COMMIT_SHA', '.']
  # Push the container image to Artifact Registry (Global Region: us-west1)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/images/api:$COMMIT_SHA']

  # Deploy container image to Cloud Run (Region: europe-west1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-europe'
    - '--image'
    - 'us-west1-docker.pkg.dev/$PROJECT_ID/images/api:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

  # Deploy container image to Cloud Run (Region: us-central1)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #   - 'run'
  #   - 'deploy'
  #   - 'api-us'
  #   - '--image'
  #   - 'us-west1-docker.pkg.dev/$PROJECT_ID/images/api:$COMMIT_SHA'
  #   - '--region'
  #   - 'us-central1'
  #   - '--platform'
  #   - 'managed'
  #   - '--allow-unauthenticated'

  # Deploy container image to Cloud Run (Region: asia-northeast1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-asia'
    - '--image'
    - 'us-west1-docker.pkg.dev/$PROJECT_ID/images/api:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/images/api:$COMMIT_SHA'