# 
# @section Building and Deploying
# API's
# @description Here we'll build and
# deploy each API. And yes, these all
# are different APIs and different
# services, that'll run on different
# domains. (subdomains)
steps:
  
  # 
  # @api Global
  # Let's now build our global API
  # and push it to Artifact Registry.
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stately-sentry-269110/api-global', 'global']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stately-sentry-269110/api-global']

  # 
  # @api Tunnels
  # API for tcp/http tunnels
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stately-sentry-269110/api-tunnels', 'tunnels']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stately-sentry-269110/api-tunnels']

  # 
  # @api Blog
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stately-sentry-269110/api-blog', 'blog']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stately-sentry-269110/api-blog']

  # 
  # @api Alias
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stately-sentry-269110/api-alias', 'alias']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stately-sentry-269110/api-alias']

  # 
  # @api Ideas
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stately-sentry-269110/api-ideas', 'ideas']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stately-sentry-269110/api-ideas']

  # 
  # @api Flow
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stately-sentry-269110/api-flow', 'flow']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stately-sentry-269110/api-flow']

  # 
  # @section Deployment
  # Here we'll deploy all docker images
  # and services to Google Cloud Run
  #  

  # @service Tunnels API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-tunnels-europe'
    - '--image'
    - 'gcr.io/stately-sentry-269110/api-tunnels'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

  # @service Global API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-europe'
    - '--image'
    - 'gcr.io/stately-sentry-269110/api-global'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

  # @service Blog API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-blog-europe'
    - '--image'
    - 'gcr.io/stately-sentry-269110/api-blog'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

  # @service Alias API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-alias-europe'
    - '--image'
    - 'gcr.io/stately-sentry-269110/api-alias'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

  # @service Ideas API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-ideas-europe'
    - '--image'
    - 'gcr.io/stately-sentry-269110/api-ideas'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

  # @service Flow API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-flow-europe'
    - '--image'
    - 'gcr.io/stately-sentry-269110/api-flow'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images: ["gcr.io/stately-sentry-269110/api-global", "gcr.io/stately-sentry-269110/api-blog", "gcr.io/stately-sentry-269110/api-tunnels", "gcr.io/stately-sentry-269110/api-ideas", "gcr.io/stately-sentry-269110/api-alias", "gcr.io/stately-sentry-269110/api-flow"]