# 
# @section Building and Deploying
# API's
# @description Here we'll build and
# deploy each API. And yes, these all
# are different APIs and different
# services, that'll run on different
# domains. (subdomains)
steps:
  
  # 
  # @api Global
  # Let's now build our global API
  # and push it to Artifact Registry.
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$GOOGLE_CLOUD_PROJECT/api-global', 'global']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$GOOGLE_CLOUD_PROJECT/api-global']

  # 
  # @api Tunnels
  # API for tcp/http tunnels
  # 
  # @region us-west1
  # @
  
  # Building container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$GOOGLE_CLOUD_PROJECT/api-tunnels', 'tunnels']
  # Pushing it to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$GOOGLE_CLOUD_PROJECT/api-tunnels']

  # 
  # @section Deployment
  # Here we'll deploy all docker images
  # and services to Google Cloud Run
  #  

  # @service Tunnels API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-tunnels-europe'
    - '--image'
    - 'gcr.io/$GOOGLE_CLOUD_PROJECT/api-tunnels'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

  # @service Global API
  # @region europe-west1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'api-europe'
    - '--image'
    - 'gcr.io/$GOOGLE_CLOUD_PROJECT/api-global'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images: ["gcr.io/$GOOGLE_CLOUD_PROJECT/api-global", "gcr.io/$GOOGLE_CLOUD_PROJECT/api-tunnels"]